README.md
pcbdraw.py

Hello, this PR adds support for several module paths as a comma seprated list:
`./pcbdraw.py <style> <libraries> <output_file> <input_file>`
Any comments are welcome ! Thanks

Add many module support as a comma separated list

---

pcbdraw.py

This was missing when using with python3.
Now, it is adding the components. I'm going to update my .svg library now.
I just added a small capacitor to test because I still don't have other components.

Fix for python3

---

examples/.gitignore
examples/init.sh

The footprint library is designed to work with v3.1 of ArduinoLearningKitStarter.
Also the aspect of the example is for this version.
If the user uses a newer version will get the idea that the script doesn't work as expected.

Checkout v3.1 of ArduinoLearningKitStarter

---

pcbdraw/pcbdraw.py

Calling Pads() is deprecated and leaks memory in DLIST_ITERATOR_WRAPPER
So we must first try PadsList(), and use Pads() only if it failed (old
API).

Fix memory leak in pcbnew (KiCad) libraries.

---

examples/pcbdraw/remap.json

This removes all the useless warnings about missing components that are
already rendered in other layers.
This patch is related to yaqwsx/PcbDraw-Lib#7

Remap invisible components from the example to dummy.

---

pcbdraw/populate.py

The first argument for find_command must be a list.
Introduced by yaqwsx/PcbDraw@f614fcc

Fix "params" relative path processing

---

pcbdraw/populate.py

There two reasons for this:
- The Debian stable version of PyYAML doesn't have yaml.FullLoader
- I think is better to use the safe version for a configuration file.
We are not using YAML for persistence.

Use yaml.safe_load instead of yaml.load

---

pcbdraw/pcbdraw.py

Messages about missing *.back component images are emitted only if the
--warn-back command line option is specified.

Make warning about back side components optional.

---

pcbdraw/pcbdraw.py

This decouples the scripts from their data.
Data can be installed in GLOBAL_DATA_DIR (/usr/share/pcbdraw/)
Footprints:
- In addition to use PKG_BASE for default libs now we also look on
GLOBAL_DATA_DIR
Styles:
- We try in the current directory.
- Then we try to add '.json' extension and look again.
- Try in PKG_BASE
- Finally try with GLOBAL_DATA_DIR
The "builtin:" mechanism bypass the search and goes straight to
PKG_BASE

Look for styles and footprints also in /usr/share/pcbdraw/

---

pcbdraw/populate.py

This decouples the scripts from their data.
Data can be installed in GLOBAL_DATA_DIR (/usr/share/pcbdraw/)
Templates:
- We try in the current directory.
- Then we try to add '.handlebars' extension and look again.
- Try in PKG_BASE
- Finally try with GLOBAL_DATA_DIR
If no template is specified we use `simple.handlebars`
Note that this PR complements #29 
This patch also avoid altering special libs ["default", "kicad-default", "eagle-default"]

Look for templates also in /usr/share/pcbdraw/

---

pcbdraw/populate.py

Now we load the mrenderer module and pcbdraw from the same directory
where populate.py is located.
In this way there is no need to install the scripts.
Neither we need to create symbolic links to run the work in progress
code.

Run populate.py without installing

---

pcbdraw/styles/oshpark-afterdark.json

This just adds a new style that looks like oshpark's after dark renders
Example

Add OSHPark After Dark style

---

pcbdraw/pcbdraw.py

This fixes the problems introduced by the new import.
A side comment: this versioneer stuff looks ugly to me. Is huge and really obstrusive for other releases systems, like the debian package.

Fixed problems when running pcbdraw without installing.

---

pcbdraw/pcbdraw.py

Drawing PCB without modules (for example edges only) were causing crash due to module variable not being None (empty list):
``` bash
aws:PcbDraw/ (master✗) $ pcbdraw --filter "" test/test/test.kicad_pcb test.svg
> /home/aws/.local/lib/python3.9/site-packages/pcbdraw/pcbdraw.py(492)get_hole_mask()
-> if module.GetPadCount() == 0:
(Pdb) type(module)
<class 'pcbnew.MODULE_List'>
(Pdb) n
[1]    351541 segmentation fault (core dumped)  pcbdraw --filter "" test/test/test.kicad_pcb test.svg
```
Using pcbnew.MODULE_List.GetFirst() before iterating through elements seems to be fixing this issue.
Run once for empty board (outline only) and once for PCB with components and it is working.

Fix drawing PCBs without modules

---

pcbdraw/pcbdraw.py

Without calling `board.SetVisibleAlls()`, at least on a certain board I was working on the bounding box will not be properly calculated (a 0 return), and the board will not be properly generated:
Before fix:  ![image](https://user-images.githubusercontent.com/15680882/146479875-bb484edb-1b6e-416e-afd3-5b26d2973069.png)
After fix: ![image](https://user-images.githubusercontent.com/15680882/146479835-cc95e44d-0c72-4fd7-bc88-c7f060cd62ed.png)
Related KiCad issue: https://gitlab.com/kicad/code/kicad/-/issues/9452

Fixed zero return with ComputeBoundingBox

---

setup.py

The project isn't using click, so we can remove it from the dependencies.

Removed click as dependency, not really used.

---

pcbdraw/pcbdraw.py

As it turns out, the `ComputeBoundingBox` returning zero was actually a bug in KiCAD, and the reply from https://gitlab.com/kicad/code/kicad/-/issues/9452 was a misintepretation/oversight. I did trace the bug eventually and reported it (https://gitlab.com/kicad/code/kicad/-/issues/10179). 
This should be now fixed in KiCAD >6.0.1, so setting all visible is no longer necessary. One consequence of setting everything  visible thought as a fix is that it also set dimension layers visible for example, so `Populate` would draw the SVG on the generated webpage to be the wrong size

Reverted #77

---

pcbdraw/ui.py

- Currently footprints contain `KiCAD-base` not `KiCAD-6`
Without this you can't even get the components from the example

Fixes the default value for --libs

---

doc/pcbdraw.md
pcbdraw/ui.py

To keep it compatible with older versions that supported `-f`

Fixes the missing shortcut for --filter (-f)

---

pcbdraw/mdrenderer.py
pcbdraw/populate.py

- mistune 2.x is incompatible with 0.8.4
- Debian stable uses 0.8.4, so installing 2.x at system level breaks all applications using mistune.
- The patch is small and the important code is shared between the two versions.

Recover mistune 0.8.4 support.

---

pcbdraw/plot.py
pcbdraw/ui.py
pcbdraw/unit.py

This PR fixes the issue raised in #117 where `unit.read_resistance` does not handle non-unit numbers.
I also took the opportunity to improve the function. Because the code calling this function expects a `decimal.InvalidOperation` if it cannot parse a number, the `read_resistance` function now attempts to parse a number and if it's unable to, it will return `InvalidOperation` which is handled by the calling function. Previously it will also return a `ValueError` which isn't handled in the calling code.

Fix #117 and Improvement on unit.read_resistance

---

pcbdraw/plot.py

In file plot.py
In _get_resistance_from_value, an "improvement" 9 month ago was not handling correctly the cases like "1 k", "270 M" as long as there was a space in the format.
in _apply_resistor_code, the call of get_style if protected from UserWarning, but get style was sending another kind of exception

Pr 1k resistor crash (#152)

---

pcbdraw/populate.py

- All resources are in SYS_PLACE/RESOURCE_TYPE/RESOURCE
- Templates are searched in SYS_PLACE/RESOURCE
- With this patch they are like other resources i.e. /usr/share/pcbdraw/templates/simple.handlebars
Otherwise I must install it at /usr/share/pcbdraw/simple.handlebars

Make system level templates dir coherent

---

pcbdraw/plot.py
pcbdraw/ui.py

This pull request adds an option to disable rendering copper layers.
For many pin diagrams, having copper traces is unnecessary.
Example with copper:
Example without copper:

Allow copper to be disabled

---

pcbdraw/mdrenderer.py
pcbdraw/mistune_shim.py
pcbdraw/populate.py
setup.py

This adds support for mistune 3.0.0 while preserving support for mistune 0.8.4 and 2.x

Support all major mistune versions
